spring:
  application:
    name: springboot-notes-app

  data:
    mongodb:
      uri: ${MONGODB_URI}

  security:
    user:
      name: user
      password: user123

    jwt:
      secret: ${JWT_SECRET}

  jmx:
    enabled: false